# Generated by Django 4.1.7 on 2023-06-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_furniture_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
