# Generated by Django 4.1.7 on 2023-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrent',
            name='available_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
