# Generated by Django 4.1.7 on 2023-06-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_ownerrent_available_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_land',
            old_name='divission',
            new_name='division',
        ),
    ]
