# Generated by Django 4.1.7 on 2023-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_divission_sell_land_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_flat',
            name='property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sell_land',
            name='property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
