# Generated by Django 4.1.7 on 2023-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_sell_flat_property_type_sell_land_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_location', models.TextField(blank=True, max_length=100, null=True)),
                ('available_time', models.CharField(blank=True, max_length=20, null=True)),
                ('km_price', models.IntegerField(blank=True, null=True)),
                ('vehicle_description', models.TextField(blank=True, max_length=250, null=True)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='rent')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
